sonar.projectKey=cfdio-frontend
sonar.projectName=cfdio-frontend
sonar.projectVersion=1.0

sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.login=sqp_930548a9b47868f429835654ddd1a2805d6e68f5

sonar.exclusions=**/node_modules/**,**/*.spec.ts